### ISSUE TITLE
That Boleyn Girl

### ISSUE THREAD

**Issue by antoinemiller** [Troubled-Mind/Suspicious-Traders#1]
**Scammer Email**: thatboleyngirltrades@hotmail.com
**Reason for addition**: User has set up trades with multiple people and never sent their end; still waiting for links months later
**Proof**: 
![IMG_3874](https://user-images.githubusercontent.com/49966416/161407807-72a0e131-3371-4a5f-b6e6-6f9694a03a4f.PNG)

**Your Discord**: spanishbabiescry#2534

**Comment by Troubled-Mind** [comment]
Thank you @antoinemiller, thatboleyngirltrades@hotmail.com has been added to the list!
